### PR TITLE
Update README with instructions to match terraform's automatic state copy behavior

### PR DESCRIPTION
**Pull request by operatingops**
I noticed while adding this to my infrastructure that you don't actually have to manually import anything, terraform will automatically move the state for you. The existing README examples use terraform version 0.11.3. I found the [terraform PR](https://github.com/hashicorp/terraform/pull/11286) where this copy behavior seems to have been added, and it is in that version so anyone following the docs should be able to use this pattern.

### CODE REVIEW

**Comment by osterman** [comment]
@operatingops sorry we let this PR slip through the cracks. 

So I am a bit confused. 
a) Yes, terraform will automatically move the state for you, but not if you are creating the state bucket in the same command
b) By calling `terraform init` second time, this "automatically moves the state"

Here's our current best known automation for this:

**Comment by operatingops** [comment]
@osterman not a worry, OSS doesn't come with an SLA :)  Thanks for taking a look!

Yup, definitely, I read through the script and we used essentially the same workflow. In this PR I was trying to stick to the existing text as much as possible and just replace the reference to the `terraform import` command with an explanation of the auto-copy (because you don't actually need to run `import`), but maybe it would be cleaner as a bulleted list of steps? If you agree it fits into this PR I can add that in, no problem. Something like the draft below to replace the Usage section.

Thanks again!

Adam

# Usage (draft)

1. Define the module in your `.tf` file using local state:
   ```hcl
   terraform {
     required_version = ">= 0.11.3"
   }

   module "terraform_state_backend" {
     source        = "git::https://github.com/cloudposse/terraform-aws-tfstate-backend.git?ref=master"
     namespace     = "cp"
     stage         = "prod"
     name          = "terraform"
     attributes    = ["state"]
     region        = "us-east-1"
   }
   ```

1. `terraform init`

1. `terraform apply`. This will create the state bucket and locking table.

1. Then add a `backend` that uses the resources:
   ```hcl
   terraform {
     required_version = ">= 0.11.3"
    
     backend "s3" {
       region         = "us-east-1"
       bucket         = "< the name of the S3 bucket >"
       key            = "terraform.tfstate"
       dynamodb_table = "< the name of the DynamoDB table >"
       encrypt        = true
     }
   }

   module "another_module" {
     source = "....."
   }
   ```

1. `terraform init`. Terraform will detect that you're trying to move your state into S3 and ask, "Do you want to copy existing state to the new backend?" Enter "yes". Now state is stored in the bucket and and the DynamoDB table will be used to lock the state to prevent concurrent modifications.

**Comment by operatingops** [comment]
P.S. I learned in #10 that I should have updated `README.yaml` and rerun the doc builds via `make`. I just pushed a commit that moves the original changes and applies the output of those commands. I'll add any other updates needed via the yaml file.

**Comment by osterman** [comment]
@operatingops these instructions look good! 

Btw, feel free to ping me on slack, if we don't respond to PRs. We're swimming in them.

**Comment by osterman** [comment]
@operatingops I like your bulleted list / markdown. Can you update the PR to look like that? =)

**Comment by operatingops** [comment]
Sweet sounds good @osterman - I updated the yaml, redid `make readme`, and pushed. It's basically the same as the bullets I put in that comment above just with a few typos fixed after I proof-read it :)

Thanks for the Slack link, this one is super low priority but I'm looking at some of the other SweetOps modules for a new project and may ping you about some new PRs if I end up pulling them in.

Enjoy the weekend!

**Comment by osterman** [comment]
Thanks @operatingops !!

**Pull request merged**
