### PR TITLE
fix: improve `prevent_unencrypted_uploads` documentation

### LINKED ISSUE #177: Variable `prevent_unencrypted_uploads` is possibly poorly named
### Describe the Feature

Since `apply_server_side_encryption_by_default` is always set, and the `EnforceTlsRequestsOnly` policy is created, uploads will always be encrypted in transit and at rest.
The way I read the behavior of the code, `prevent_unencrypted_uploads` is simply enforcing that all uploads _must_ specify an at-rest encryption key, and therefore bypass the default encryption.

### Expected Behavior

Would a better name be `prevent_default_encryption`? Or modify the documentation in the `README` to better describe the functionality. The way it reads now, it sounds like without `prevent_unencrypted_uploads`, uploads would be unencrypted.

### Use Case

When using the module, I couldn't upload files to the Terraform state without specifying a key (including using the AWS Console). When I disabled `prevent_default_encryption`, I confirmed that the file I uploaded was indeed encrypted with the default encryption key (SSE-S3).

### Describe Ideal Solution

Either change the variable name, or the accompanying documentation in the README so that new users of the module don't need to read the code in order to understand the behavior.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pazaan**
## what

Update documentation for the `prevent_unencrypted_uploads` variable to more clearly explain its behavior.

## references
* Closes #177

## notes
I also opened a [PR on the CI job](https://github.com/cloudposse/.github/pull/115) to [fix this job error](https://github.com/cloudposse/terraform-aws-tfstate-backend/actions/runs/9797916695/job/27055456433)

### CODE REVIEW

**Review by gberenice — DISMISSED** [review]

**Comment by gberenice** [comment]
@pazaan could you please add one more change to `examples/complete/variables.tf` to satisfy tflint:
```
  variables.tf:6:1: warning: variable "arn_format" is declared but not used ()
```

**Comment by gberenice** [comment]
Thank you, @pazaan 👏

**Review by gberenice — APPROVED** [review]

**Comment by gberenice** [comment]
@cloudposse/approvers please review this as a code owner.

**Review by Nuru — CHANGES_REQUESTED** [review]
@pazaan As I explained [here](https://github.com/cloudposse/terraform-aws-tfstate-backend/issues/177#issuecomment-2242197733), I believe you are wrong about the impact of the setting, and therefore I believe the updated description is still misleading and not appropriate.

**Pull request closed without merging**
