### PR TITLE
Extend S3 bucket policy to ensure encryption-in-transit

### PR DESCRIPTION
**Pull request by bazbremner**
Whilst the current option policy ensures server-side encryption,
encryption of the transport mechanism isn't enforced.

This change extends the S3 bucket policy to enforce encryption in
transit, which is necessary to satisfy the s3-bucket-ssl-requests-only
AWS Config Rule[1]

Given the option to prevent unencrypted uploads is already present,
and this change fits in the spirit of that, I've not introduced a
separate flag for this behaviour.

[1] https://docs.aws.amazon.com/config/latest/developerguide/s3-bucket-ssl-requests-only.html

### CODE REVIEW

**Comment by bazbremner** [comment]
@maximmi looks like the existing tests are failing because the README hasn't changed.

There's no configurable change and I didn't think it was noteworthy enough to update the README, yet the tests enforce it. Do you have any suggestions (or fixes for the tests)?

**Comment by bazbremner** [comment]
@maximmi I strongly recommend pulling Actions and/or README related changes to get the build passing out into another PR so master works, then I can open a new PR with just my changes rebased against the updated master.

Right now this PR is changing several things at once.

**Comment by maximmi** [comment]
@bazbremner here is new release: https://github.com/cloudposse/terraform-aws-tfstate-backend/releases/tag/0.16.0

**Comment by bazbremner** [comment]
@maximmi Thanks!

**Pull request merged**
