### PR TITLE
tfsec ignores added

### PR DESCRIPTION
**Pull request by davenicoll**
## what

* added tfsec ignores to false positives

## why

* the terraform `aws_s3_bucket` resource was updated some time ago to deprecate access policies, encryption and logging as arguments, instead preferring separate terraform resources. tfsec incorrectly highlights the `aws_s3_bucket` resource are CRITICALly vulnerable.

## references

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#argument-reference

### CODE REVIEW

**Comment by max-lobur** [comment]
@jamengual `/terratest` is the new command

**Review by jamengual — APPROVED** [review]

**Pull request merged**
