### PR TITLE
Adds check to only write backend config file if path doesn't exist

### PR DESCRIPTION
**Pull request by Gowiem**
## what
* This allows users to edit the backend config file once written and not have to worry about it being overwritten by the module due to changes.

## why
* Any changes to the backend.tf file are overwritten on the next apply, which can be annoying if trying to specify additional `required_providers`, `required_version`, or other terraform configuration block changes. This updates the template file block so that file is not overwritten if the backend.tf (or other terraform config file name) already exists.

### CODE REVIEW

**Comment by osterman** [comment]
I can see the value of this but also for the original functionality. Can we add a flag to enable the overwrite functionality and default it to true to maintain behavior

**Comment by Gowiem** [comment]
@osterman Done... though it's late on a Friday and I definitely second guessed myself on the logic. Give it a keen eye if you don't mind!

**Comment by Gowiem** [comment]
Released as [0.19.0](https://github.com/cloudposse/terraform-aws-tfstate-backend/releases/tag/0.19.0)

**Pull request merged**
