### PR TITLE
Make public access lock optional

### PR DESCRIPTION
**Pull request by RothAndrew**
## what

* Make the S3 Bucket Public Access Block optional by introducing a new variable `enable_public_access_block` with default of `true` to preserve previous behavior

## why

* To be perfectly honest, because my company for some unknown reason has the ability to create the public access block on their deny list.
* More generally, it adds a bit more flexibility with only tiny added complexity. If people don't use it, the module will function no differently than before this variable was added.

## references

* none

## notes

* I'm not sure why so much changed in the readme. I ran `make init` and `make readme`. Maybe a change in the version of `terraform-docs`?

### CODE REVIEW

**Comment by RothAndrew** [comment]
Thanks @Gowiem. Let's wait to merge this though until the chatops has been added. I'm submitting the PR for that in a few minutes.

**Comment by Gowiem** [comment]
@RothAndrew I think we need @osterman or someone from CP to merge due to the old CodeFresh test.

**Pull request merged**
