### PR TITLE
Custom bucket policy statements

### PR DESCRIPTION
**Pull request by feraudet**
## what

Add the ability to include custom bucket policy statements

## why

Sometime we need to allow someone else to access to tfstates. Ex: Allow the entire orgs to access to some states

### CODE REVIEW

**Comment by Gowiem** [comment]
@feraudet thanks for the contribution, but I believe this is possible via the `source_policy_documents` variable. Please check that out, try it out within your own project, and then report back and reopen if needed. If there is a need here, we're happy to look into it, but I believe this is already accounted for. Thanks!

**Comment by feraudet** [comment]
Hello,
As far as I understand source_policy_documents only allow to override existing policies, not to add policies

**Comment by feraudet** [comment]
I think your'e right, according to the documentation, using blank Sid allow to add policies

**Comment by Gowiem** [comment]
@feraudet yeah and it is confusing due to the terminology, so it makes sense to not get it at first. Try it out and let me know how it goes!

**Pull request closed without merging**
