### PR TITLE
Add GitHub Actions ChatOps according to the docs

### PR DESCRIPTION
**Pull request by RothAndrew**
## what
* Add GitHub Actions ChatOps according to the [docs](https://docs.cloudposse.com/community/automated-testing/#chatops-configuration)

## why
* Migration to GitHub actions from Codefresh

## references
* https://docs.cloudposse.com/community/automated-testing/

## notes
* I'm not sure what the process is for adding the new badge. Recommend adding more detailed instructions to the docs

### CODE REVIEW

**Comment by RothAndrew** [comment]
Looks like chatops doesn't work until after the migration is merged to master?

@Gowiem, mind reviewing this one as well?

**Comment by Gowiem** [comment]
@RothAndrew Looks good, but you have to delete `.github/workflows/slash-command-dispatch.yml` -- Then should be good to ship.

**Comment by RothAndrew** [comment]
> @RothAndrew Looks good, but you have to delete `.github/workflows/slash-command-dispatch.yml` -- Then should be good to ship.

done

**Pull request merged**
